### ISSUE TITLE
OperationalError: no such table

### ISSUE THREAD

**Issue by wkfunk** [wkfunk/django_kappa#11]
(django_kappa)keith@keith-x220:~/code/django_kappa$ python manage.py syncdb
Traceback (most recent call last):
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):                                                                                                                                                       [104/614]
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: surveys_surveystatus

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/debug_toolbar/settings.py", line 232, in patch_all
    patch_root_urlconf()
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/debug_toolbar/settings.py", line 220, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/core/urlresolvers.py", line 550, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/core/urlresolvers.py", line 352, in app_dict
    self._populate()
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/core/urlresolvers.py", line 285, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/keith/code/django_kappa/django_kappa/urls.py", line 24, in <module>
    url(r'^surveys/', include('surveys.urls', namespace="surveys")),
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load                                                                                                                      [52/614]
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/keith/code/django_kappa/surveys/urls.py", line 2, in <module>
    from . import views
  File "/home/keith/code/django_kappa/surveys/views.py", line 15, in <module>
    class IndexView(generic.ListView):
  File "/home/keith/code/django_kappa/surveys/views.py", line 20, in IndexView
    SurveyStatus.objects.all()])
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/keith/.virtualenvs/django_kappa/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: surveys_surveystatus

**Comment by wkfunk** [comment]
Comment out `django-debug-toolbar` from `settings.py`, run `syncdb`, then uncomment it back out.
