### ISSUE TITLE
OperationalError: table already exists

### ISSUE THREAD

**Issue by wkfunk** [wkfunk/django_kappa#16]
(kappa2)keith@keith-x220:~/code/kappa2/django_kappa$ python manage.py migrate surveys
Operations to perform:
  Apply all migrations: surveys
Running migrations:
  Rendering model states... DONE
  Applying surveys.0001_initial...Traceback (most recent call last):
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: table "surveys_answerbase" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
  Rendering model states... DONE                                                                                                                                                        [208/1822]
  Applying surveys.0001_initial...Traceback (most recent call last):
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: table "surveys_answerbase" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/keith/.virtualenvs/kappa2/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "surveys_answerbase" already exists

**Comment by wkfunk** [comment]
`python manage.py migrate surveys --fake-initial`
